### ISSUE TITLE
Environmental Variable 

### ISSUE THREAD

**Issue by sshort325** [segrelab/comets-toolbox#7] opened 2022-06-28 16:52 UTC
![Screen Shot 2022-06-28 at 10 23 22 AM](https://user-images.githubusercontent.com/107510978/176236433-449011bb-a70a-41bf-8ece-14f00eb23031.png)
I keep getting this issue and I'm not sure how to fix it.

**Comment by dukovski** [comment] 2022-06-28 17:09
You did not install COMETS and Gurobi properly. The COMETS_HOME variable tells matlab where comets was installed. In Windows you go to setting->advanced->set ENV variables. In Linux/Mac you should have a line in your .bashrc or .cshrc files:

export COMETS_HOME=<path to comets>
export GUROBI_HOME=<path to gurobi>

where <path to comets> and <path to gurobi> are replaced with your actual paths.

**Comment by sshort325** [comment] 2022-06-28 17:14
Oh my gosh thank you so much! I am really new to this and not very good at this point honestly. How do I find my path on a Mac? Also, if I find my path and do the export does that fix it? Or do I need to completely redownload?

**Comment by dukovski** [comment] 2022-06-28 17:21
Oh no, you don't need to do any of that, just use the installer from runcomets.org

**Comment by dukovski** [comment] 2022-06-28 17:22
https://www.runcomets.org/get-started

**Comment by dukovski** [comment] 2022-06-28 17:23
Also, detailed instruction can be found here: https://www.nature.com/articles/s41596-021-00593-3

**Comment by dukovski** [comment] 2022-06-28 17:24
specific details are in this section: https://www.nature.com/articles/s41596-021-00593-3#Sec24

**Comment by dukovski** [comment] 2022-06-28 17:25
In MacOS, the line

export GUROBI_HOME=/Library/gurobi902/mac64/

should be included in the .bash_profile file in older versions of MacOS, or .zshrc in the latest version of MacOS. The version name and number in gurobi902 should be set to the one installed. It is important to source these files before attempting to run COMETS. The easiest way to do that is to close the terminal and open another one.

Also, the COMETS installer will add lines:

export COMETS_HOME=/home/username/comets export PATH=$PATH:$COMETS_HOME export GUROBI_COMETS_HOME=$(echo $(ls -d /usr/gurobi/gurobi*/linux64)|awk {‘print $NF’}) export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GUROBI_COMETS_HOME/lib/

in the.bashrc file in Linux, and

export COMETS_HOME=/Applications/COMETS export PATH=$PATH:$COMETS_HOME export GUROBI_COMETS_HOME=$(echo $(ls -d /Library/gurobi*/mac64)|awk {‘print $NF’}) export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GUROBI_COMETS_HOME/lib/

in the .bash_profile file in older versions of MacOS, and .zshrc in the latest version of MacOS, where username is replaced with the specific one for the user. This should make Gurobi libraries available to COMETS. More information can be found in the Troubleshooting table.

**Comment by sshort325** [comment] 2022-06-28 17:27
I do have those instructions, I have been following along with them as best as I can. On page 5042, I was following adding those lines in. However, it wasn't working well. I did download the COMETS through the link you posted. I am just really confused on this part. 
![Screen Shot 2022-06-28 at 11 24 56 AM](https://user-images.githubusercontent.com/107510978/176245221-81e5b66d-374a-492d-b051-bc73677f4b0a.png)

**Comment by dukovski** [comment] 2022-06-28 17:32
All this is supposed to be done automatically during installation. 
Can you look at your .zshrc file? Open a terminal and do:
cat .zshrc

**Comment by dukovski** [comment] 2022-06-28 17:37
Actually, let's go back a bit. Did you use the installer for Mac from runcomets.org?

**Comment by sshort325** [comment] 2022-06-28 17:40
Honestly, I started this process a few weeks ago and Im not 100% sure. But none of that information has come up automatically for me.

**Comment by dukovski** [comment] 2022-06-28 17:47
OK get the installer from here: https://www.runcomets.org/installation for Mac, and just run it.  Let me know hoe it goes.

**Comment by sshort325** [comment] 2022-06-28 17:50
![Screen Shot 2022-06-28 at 11 49 31 AM](https://user-images.githubusercontent.com/107510978/176249385-8b777601-ef92-4496-bda8-87aa632a7565.png)
I did, that's how COMETS looks.

**Comment by sshort325** [comment] 2022-06-28 17:50
![Screen Shot 2022-06-28 at 11 49 56 AM](https://user-images.githubusercontent.com/107510978/176249477-3e6a2b2d-5245-43c3-91c8-c36222bbf2d7.png)
And that's what I got in my terminal

**Comment by dukovski** [comment] 2022-06-28 17:51
OK that's good

**Comment by dukovski** [comment] 2022-06-28 17:52
So the problem is when  you try to run the matlab toolbox, right?

**Comment by dukovski** [comment] 2022-06-28 17:53
Did you add the paths to comets and cobra in matlab?

**Comment by dukovski** [comment] 2022-06-28 17:54
Would you try the cometspy toolbox in pyhton, it is easier to setup.

**Comment by dukovski** [comment] 2022-06-28 17:55
Oh sorry, I missed one of the warnings. Seems like you don't have gurobi installed. Did you try to install gurobi?

**Comment by sshort325** [comment] 2022-06-28 17:56
Yes thats correct. When I do testComets() it comes up with the environment variable output from above.
![Screen Shot 2022-06-28 at 11 55 39 AM](https://user-images.githubusercontent.com/107510978/176250408-5ef6f041-29eb-4811-a8be-59aa6cb629d2.png)

**Comment by sshort325** [comment] 2022-06-28 17:57
I was actually working in python when I had this happen. And that's why I switched to Matlab. 
![Screen Shot 2022-06-23 at 2 37 04 PM](https://user-images.githubusercontent.com/107510978/176250570-3e8e3d28-bd01-4a90-845d-e22ad210e655.png)

**Comment by dukovski** [comment] 2022-06-28 17:58
Let's try to make it work in python.

**Comment by dukovski** [comment] 2022-06-28 18:02
Open a terminal, do:

cd
cat .zshrc 

Let's see if you have GUROBI_HOME properly installed.

**Comment by sshort325** [comment] 2022-06-28 18:04
![Screen Shot 2022-06-28 at 12 04 34 PM](https://user-images.githubusercontent.com/107510978/176251981-83082dd0-989c-49d3-9d13-006c75830050.png)

**Comment by dukovski** [comment] 2022-06-28 18:07
This is surprising.
Do:

cat .bash_profile

**Comment by sshort325** [comment] 2022-06-28 18:10
![Screen Shot 2022-06-28 at 12 10 12 PM](https://user-images.githubusercontent.com/107510978/176252947-164b5b65-f16b-45ec-b9db-108824df9955.png)

**Comment by dukovski** [comment] 2022-06-28 18:23
OK let's see where is Gurobi installed. Do:
echo $GUROBI_COMETS_HOME

**Comment by dukovski** [comment] 2022-06-28 18:23
and then:
echo $GUROBI_HOME

**Comment by sshort325** [comment] 2022-06-28 18:25
![Screen Shot 2022-06-28 at 12 25 43 PM](https://user-images.githubusercontent.com/107510978/176255631-d8a5215e-b97f-4a75-b9a3-257d3054852d.png)

**Comment by dukovski** [comment] 2022-06-28 18:27
aha, this is it, gurobi is not installed where it is supposed to be
They could have changed the default installation for gurobi

**Comment by gbkgwyneth** [comment] 2022-06-28 18:28
Please note that as of Gurobi 9.5.0 the install directory on Macs has changed:
/Library/gurobi950/macos_universal2

**Comment by dukovski** [comment] 2022-06-28 18:28
Ah, that's it.

**Comment by dukovski** [comment] 2022-06-28 18:29
OK so in the .bash_profile file you should make that change.

**Comment by sshort325** [comment] 2022-06-28 18:30
How do I change it?

**Comment by dukovski** [comment] 2022-06-28 18:32
export GUROBI_COMETS_HOME=/Library/gurobi950/macos_universal2/
export GUROBI_HOME=/Library/gurobi950/macos_universal2/

**Comment by dukovski** [comment] 2022-06-28 18:32
Edit your .bash_profile file and replace those two lines.

**Comment by dukovski** [comment] 2022-06-28 18:34
Do you know how to do it?

**Comment by sshort325** [comment] 2022-06-28 18:35
I googled it just now. This is what it looks like now, I highlighted it to make it easier to see.
![Screen Shot 2022-06-28 at 12 35 33 PM](https://user-images.githubusercontent.com/107510978/176257284-559b059d-045f-4400-a35d-9d176b29c37f.png)

**Comment by dukovski** [comment] 2022-06-28 18:38
OK good, now you need to restart your Mac in principle. Can you do that?

**Comment by dukovski** [comment] 2022-06-28 18:38
(If you don't want to restart there is a way around it)

**Comment by sshort325** [comment] 2022-06-28 18:39
I think Ill be okay to restart it. Ill be right back

**Comment by dukovski** [comment] 2022-06-28 18:39
OK

**Comment by sshort325** [comment] 2022-06-28 18:43
Alright, all restarted now

**Comment by dukovski** [comment] 2022-06-28 18:43
OK let's try the echoes again

**Comment by dukovski** [comment] 2022-06-28 18:44
echo $GUROBI_COMETS_HOME

**Comment by sshort325** [comment] 2022-06-28 18:46
![Screen Shot 2022-06-28 at 12 46 40 PM](https://user-images.githubusercontent.com/107510978/176259052-f6753204-7327-4b2a-856b-1e2d0693cf21.png)

**Comment by dukovski** [comment] 2022-06-28 18:48
I think you have a line with GUROBI_COMETS_HOME still present in your .bash_profile file.

**Comment by dukovski** [comment] 2022-06-28 18:48
the old one

**Comment by sshort325** [comment] 2022-06-28 18:48
Oh crap yes I didnt delete that

**Comment by dukovski** [comment] 2022-06-28 18:48
You have to comment it out

**Comment by dukovski** [comment] 2022-06-28 18:50
so you need to have only one line with GUROBI_COMETS_HOME in the file

**Comment by sshort325** [comment] 2022-06-28 18:50
Comment? Oh okay, I think I have a few so I just want the new one

**Comment by dukovski** [comment] 2022-06-28 18:51
Yup

**Comment by sshort325** [comment] 2022-06-28 18:55
![Screen Shot 2022-06-28 at 12 55 14 PM](https://user-images.githubusercontent.com/107510978/176260591-d5cc2cd4-999f-4116-ad02-ab6d8cb0b510.png)
Got it that time

**Comment by dukovski** [comment] 2022-06-28 20:15
Great, does cometspy work now?

**Comment by sshort325** [comment] 2022-06-28 22:40
Im not sure this is what I get when I do the first part of "Loading the COMETS Python Toolbox"
![Screen Shot 2022-06-28 at 4 39 00 PM](https://user-images.githubusercontent.com/107510978/176316205-2786ba4c-457b-45f7-b471-357ccecfd561.png)

**Comment by dukovski** [comment] 2022-06-29 00:00
This is a problem with cobra now. You need to install it properly. 
Do it on anaconda shell
$ pip install cobra

**Comment by sshort325** [comment] 2022-06-29 00:54
Where do I find the anaconda shell?

**Comment by sshort325** [comment] 2022-06-29 00:57
![Screen Shot 2022-06-28 at 6 57 03 PM](https://user-images.githubusercontent.com/107510978/176328545-d9842547-9e51-4901-bb11-709cf716dfb2.png)

**Comment by dukovski** [comment] 2022-06-29 13:43
You can actually do it in a regular terminal.

**Comment by dukovski** [comment] 2022-06-29 13:44
Follow the instructions in cobrapy. https://opencobra.github.io/cobrapy/

**Comment by sshort325** [comment] 2022-06-29 17:02
![Screen Shot 2022-06-29 at 11 01 24 AM](https://user-images.githubusercontent.com/107510978/176494202-6916141e-c639-4e6d-ba0a-6dbec4dcd973.png)
This is what I get after following the pip install cobra

**Comment by sshort325** [comment] 2022-06-29 17:03
![Screen Shot 2022-06-29 at 11 00 44 AM](https://user-images.githubusercontent.com/107510978/176494408-5d074a53-e468-4e3e-88c2-abaebb7af04a.png)
And i get the same in my python

**Comment by dukovski** [comment] 2022-06-29 18:09
Hm, not sure. Look at this discussion: https://groups.google.com/g/cobra-pie/c/G4b1bFwmkSk

**Comment by sshort325** [comment] 2022-06-29 18:16
I found out it's because "Cobra.test" has been deprecated for the newer "load_model", so it is fixed for me now. Thank you so much for all your help! I really appreciate it!

**Comment by dukovski** [comment] 2022-06-29 18:17
Great, so comets is running now?

**Comment by sshort325** [comment] 2022-06-29 18:37
I did the "import cometspy as c" and it works just fine. It just let me know that I haven't used it yet.

**Comment by dukovski** [comment] 2022-06-29 18:40
Great, have fun with it. Can you tell me who you are, what university and what you will be using it for? Thx.

**Comment by sshort325** [comment] 2022-06-29 18:50
Yes. My name is Samantha Short, for Carroll College in Montana. Maize Microbiome Modeling Project: Predict bacterial metabolic and growth responses (individually and in the community) to different nutrient sources, which I thought would be really interesting to explore with COMETS and to see how spatiotemporal dynamics plays a role.

**Comment by dukovski** [comment] 2022-06-29 18:52
That's fantastic. Please contact me if you need any additional help with comets. I will close this issue now, if that's fine with you.

**Comment by sshort325** [comment] 2022-06-29 18:56
Yes, thank you again for all your help! I will reach out if I have any other issues.

**Closed as completed** 2022-06-29 18:57 UTC
